apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdpcr
  namespace: vdpcr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vdpcr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vdpcr
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vdpcr
      containers:
        - name: vdpcr
          image: logikone/vdpcr:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
