apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vdpcr
  namespace: vdpcr
spec:
  targetCPUUtilizationPercentage: 90
  minReplicas: 3
  maxReplicas: 9
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vdpcr